name: obmin
description: "Obmin"
version: 0.0.1
homepage: https://github.com/prokhor-andrew/obmin-flutter.git

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.4.0
  fast_immutable_collections: ^10.2.4
  meta: ^1.12.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  source_gen: ^1.5.0
  build_runner: ^2.4.11

